### ISSUE TITLE
Change tests license agpl3+ to gpl3+

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud-libraries/nextcloud-router#645]
Hi @Antreesy and @susnux 

all test in https://github.com/nextcloud-libraries/nextcloud-router/tree/main/__tests__ creted/modified by you are labelled agpl3+ (copy&paste I expect) while the library itself is gpl3+ 

So to harmonize that I would like to change the license of the tests to gpl3+ as well with your consent!

What do you say?

**Comment by susnux** [comment]
Yes and this counts for all my work on this libraries here, I am ok with `LGPL-3.0-or-later`. `GPL-3.0-or-later`, `AGPL-3.0-or-later`.

**Comment by AndyScherzinger** [comment]
Fixed and merged, thanks for the feedback 👍
